# Generated by Django 6.0.7 on 2026-08-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
