# Generated by Django 5.1.4 on 2026-09-05 22:41

from django.db import migrations, models
from django.utils.text import slugify


def generar_slugs_jerarquicos(apps, schema_editor):
    """Genera slugs jerárquicos para categorías existentes."""
    Categoria = apps.get_model('categories', 'Categoria')
    
    for categoria in Categoria.objects.all():
        # Generar slug jerárquico
        nombre_slug = slugify(categoria.nombre)
        
        if not categoria.id_categoria_padre:
            categoria.slug = nombre_slug
        else:
            # Construir slug jerárquico
            slugs_padres = []
            padre = categoria.id_categoria_padre
            
            while padre:
                slugs_padres.insert(0, slugify(padre.nombre))
                padre = padre.id_categoria_padre
            
            slugs_padres.append(nombre_slug)
            categoria.slug = "-".join(slugs_padres)
        
        categoria.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoria_padre_orden'),
    ]

    operations = [
        # Paso 1: Agregar campo slug sin unique=True
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=False),
        ),
        # Paso 2: Generar slugs para datos existentes
        migrations.RunPython(generar_slugs_jerarquicos, migrations.RunPython.noop),
        # Paso 3: Cambiar slug a unique=True
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        # Paso 4: Eliminar unique=True de nombre
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        # Paso 5: Agregar constraint unique por (padre, nombre)
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('id_categoria_padre', 'nombre'), name='unique_nombre_por_padre', violation_error_message='Ya existe una categoría con este nombre bajo el mismo padre.'),
        ),
    ]
