# Generated by Django 6.0.7 on 2026-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0006_alter_producto_options_producto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'variante'), name='uniq_item_por_variante_en_carrito'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_item_cantidad_positiva'),
        ),
    ]
