# Generated by Django 6.0.7 on 2026-08-12 18:44

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_auth_django'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.users.models.UsuarioManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(condition=models.Q(('predeterminada', True)), fields=('usuario',), name='uniq_direccion_predeterminada_por_usuario'),
        ),
    ]
