# Generated by Django 4.2.7 on 2026-08-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_compra', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('direccion', models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.PROTECT, to='users.direccion')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.compra')),
                ('variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.PROTECT, to='products.variante')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='orders.metodopago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='users.usuario'),
        ),
    ]
