# Generated by Django 6.0.7 on 2026-08-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
    ]

# Generated by Django 6.0.7 on 2026-08-21 16:52

from django.db import migrations


def crear_metodos_pago(apps, schema_editor):
    MetodoPago = apps.get_model('orders', 'MetodoPago')
    
    metodos = [
        {
            "tipo": "Wompi",
            "detalle": "Pasarela de pagos segura con tarjetas de crédito/débito"
        },
        {
            "tipo": "Contra entrega",
            "detalle": "Pagar al recibir el pedido en efectivo"
        },
        {
            "tipo": "Transferencia bancaria",
            "detalle": "Transferencia directa a cuenta bancaria"
        }
    ]
    
    for metodo_data in metodos:
        MetodoPago.objects.get_or_create(
            tipo=metodo_data["tipo"],
            defaults={"detalle": metodo_data["detalle"]}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_metodos_pago, migrations.RunPython.noop),
    ]
