# Generated by Django 6.0.7 on 2026-08-14 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.PROTECT, to='users.direccion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='size_variant',
            field=models.ForeignKey(db_column='id_size_variant', on_delete=django.db.models.deletion.PROTECT, to='products.sizevariant'),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='orders.metodopago'),
        ),
    ]
