# Generated by Django 6.0.7 on 2026-08-12 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_compra_telefono_contacto'),
        ('products', '0006_alter_producto_options_producto_created_at_and_more'),
        ('users', '0004_alter_usuario_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['usuario', '-fecha_compra'], name='idx_compra_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado_compra'], name='idx_compra_estado'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_compra_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='chk_detalle_precio_no_negativo'),
        ),
    ]
