# Generated by Django 5.1.4 on 2026-09-08 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_compra_nombre_cliente_alter_compra_direccion_and_more'),
        ('products', '0002_alter_variante_color_alter_variante_talla'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resena',
            name='compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', help_text='Compra asociada (obligatoria para nuevas reseñas, nullable para históricas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='orders.compra'),
        ),
        migrations.AddField(
            model_name='resena',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre del cliente al momento de la reseña (snapshot para invitados)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.PositiveSmallIntegerField(help_text='Calificación del 1 al 5'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', help_text='Usuario (opcional para reseñas de invitados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('compra', 'producto')},
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='calificacion_rango_valido'),
        ),
    ]
