# Generated by Django 6.0.7 on 2026-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
