# Generated by Django 5.1.4 on 2026-09-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='datos_aceptados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='terminos_aceptados',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia_transaccion',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
