# Generated by Django 6.0.7 on 2026-08-21 18:45

from django.db import migrations, models


def add_wompi_transaction_id_field(apps, schema_editor):
    """Agregar el campo wompi_transaction_id si no existe"""
    Pago = apps.get_model('payments', 'Pago')
    
    # Verificar si el campo ya existe en el modelo
    try:
        # Intentar acceder al campo
        field = Pago._meta.get_field('wompi_transaction_id')
        # Si existe, no hacer nada
        return
    except:
        pass
    
    # Si no existe, agregarlo usando SQL directo
    db_type = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        if db_type == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'pagos'
                AND column_name = 'wompi_transaction_id'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE pagos
                    ADD COLUMN wompi_transaction_id VARCHAR(120) NULL
                """)
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS idx_pagos_wompi_transaction_id
                    ON pagos(wompi_transaction_id)
                """)
        elif db_type == 'sqlite':
            cursor.execute("PRAGMA table_info(pagos)")
            columns = [col[1] for col in cursor.fetchall()]
            if 'wompi_transaction_id' not in columns:
                cursor.execute("""
                    ALTER TABLE pagos
                    ADD COLUMN wompi_transaction_id VARCHAR(120) NULL
                """)
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS idx_pagos_wompi_transaction_id
                    ON pagos(wompi_transaction_id)
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pago_wompi_transaction_id'),
    ]

    operations = [
        migrations.RunPython(add_wompi_transaction_id_field, migrations.RunPython.noop),
    ]
