# Generated by Django 6.0.7 on 2026-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ensure_wompi_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='datos_aceptados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='terminos_aceptados',
            field=models.BooleanField(default=False),
        ),
    ]
