# Generated by Django 6.0.7 on 2026-08-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_metodos_pago'),
        ('payments', '0004_pago_datos_aceptados_pago_fecha_aceptacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiWebhookEvent',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('estado_procesamiento', models.CharField(choices=[('recibido', 'Recibido'), ('procesado', 'Procesado'), ('ignorado', 'Ignorado'), ('error', 'Error')], default='recibido', max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wompi_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='acceptance_token_usado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='personal_data_auth_token_usado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia_transaccion',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('confirmada', 'Confirmada'), ('liberada', 'Liberada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('compra', models.OneToOneField(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='reserva_stock', to='orders.compra')),
            ],
            options={
                'db_table': 'reservas_stock',
                'indexes': [models.Index(fields=['estado', 'fecha_expiracion'], name='idx_reserva_estado_exp')],
            },
        ),
    ]
