# Generated by Django 4.2.7 on 2026-08-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_delete_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Valor fijo')], default='porcentaje', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='products.producto')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
    ]
