# Generated by Django 6.0.7 on 2026-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoria_padre_orden'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='ofertas', to='categories.categoria'),
        ),
    ]
