# Generated by Django 6.0.7 on 2026-08-14 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'colores',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tallas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('archivado', 'Archivado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='categories.categoria')),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['-created_at', 'id_producto'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id_variante', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(db_column='id_color', on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
                ('talla', models.ForeignKey(db_column='id_talla', on_delete=django.db.models.deletion.PROTECT, to='products.talla')),
            ],
            options={
                'db_table': 'producto_variantes',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.URLField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('principal', models.BooleanField(default=False)),
                ('variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='products.variante')),
            ],
            options={
                'db_table': 'producto_imagenes',
            },
        ),
    ]
