# Generated by Django 6.0.7 on 2026-08-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'colores',
            },
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id_variante', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.ForeignKey(blank=True, db_column='id_color', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.color')),
            ],
            options={
                'db_table': 'producto_colores',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.URLField(blank=True, max_length=500)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('principal', models.BooleanField(default=False)),
                ('color_variant', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant')),
            ],
            options={
                'db_table': 'producto_imagenes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='categories.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='products.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='colorvariant',
            unique_together={('producto', 'color')},
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id_size_variant', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_variant', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant')),
            ],
            options={
                'db_table': 'producto_tallas',
                'unique_together': {('color_variant', 'talla')},
            },
        ),
    ]
