# Generated by Django 6.0.7 on 2026-08-21 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='color',
            field=models.ForeignKey(blank=True, db_column='id_color', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.color'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='talla',
            field=models.ForeignKey(blank=True, db_column='id_talla', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.talla'),
        ),
    ]
