# Generated by Django 6.0.7 on 2026-08-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colorvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sizevariant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='colorvariant',
            constraint=models.UniqueConstraint(fields=('producto', 'color'), name='unique_producto_color'),
        ),
        migrations.AddConstraint(
            model_name='sizevariant',
            constraint=models.UniqueConstraint(fields=('color_variant', 'talla'), name='unique_color_variant_talla'),
        ),
        migrations.RemoveField(
            model_name='sizevariant',
            name='precio',
        ),
    ]
