# Generated by Django 5.1.4 on 2026-09-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_variante_color_alter_variante_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id_diseño', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'diseños',
            },
        ),
        migrations.AddField(
            model_name='variante',
            name='diseño',
            field=models.ForeignKey(blank=True, db_column='id_diseño', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.diseño'),
        ),
    ]
