# Generated by Django 5.1.4 on 2026-09-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_diseño_variante_diseño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
