# Generated by Django 6.0.7 on 2026-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_categoria_imagen_alter_categoria_descripcion'),
        ('products', '0006_alter_producto_options_producto_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado', 'categoria', '-created_at'], name='idx_producto_estado_cat'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['producto', 'stock'], name='idx_variante_producto_stock'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='chk_producto_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('producto', 'color', 'talla'), name='uniq_variante_producto_color_talla'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='chk_variante_stock_no_negativo'),
        ),
    ]
